# Generated by Django 4.0.5 on 2022-06-23 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangowedapp1', '0002_venue_venue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='Venue',
        ),
    ]
