# Generated by Django 4.0.5 on 2022-06-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangowedapp1', '0004_venue_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
    ]
